### ISSUE TITLE
Failed to deobfuscate

### ISSUE THREAD

**Issue by eftehassanpp** [glizzykingdreko/Datadome-Interstitial-Deobfuscator#2]
while trying to Deobfuscate Interestitial v 1.10.1 getting the following error

```
<><><><><><><><>< Datadome Interstitial Deobfuscator ><><><><><><><><>
> Extracted decode array name: oc
> Replaced 52542 function calls with their results
> Replaced 14379 function calls with their results
> Extracted decode array
evalmachine.<anonymous>:35
        o[n](r, r.exports, e), i = 141;
            ^

TypeError: o[n] is not a function
    at e (evalmachine.<anonymous>:35:13)
    at evalmachine.<anonymous>:1:1
    at Script.runInContext (node:vm:134:12)
    at Object.runInContext (node:vm:280:6)
    at CallExpression (c:\Users\USER\Desktop\dd-regular-deob\Datadome-Interstitial-Deobfuscator\transformers\evaluateStringObf.js:139:35)
    at NodePath._call (c:\Users\USER\Desktop\dd-regular-deob\Datadome-Interstitial-Deobfuscator\node_modules\@babel\traverse\lib\path\context.js:46:20)
    at NodePath.call (c:\Users\USER\Desktop\dd-regular-deob\Datadome-Interstitial-Deobfuscator\node_modules\@babel\traverse\lib\path\context.js:36:17)
    at NodePath.visit (c:\Users\USER\Desktop\dd-regular-deob\Datadome-Interstitial-Deobfuscator\node_modules\@babel\traverse\lib\path\context.js:82:31)
    at TraversalContext.visitQueue (c:\Users\USER\Desktop\dd-regular-deob\Datadome-Interstitial-Deobfuscator\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitMultiple (c:\Users\USER\Desktop\dd-regular-deob\Datadome-Interstitial-Deobfuscator\node_modules\@babel\traverse\lib\context.js:61:17)

Node.js v20.8.1
```

**Comment by glizzykingdreko** [comment]
Paid updates/solutions for datadome -> glizzykingdreko@protonmail.com
